# Generated by Django 3.1.5 on 2021-02-04 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20210204_1813'),
    ]
