# Generated by Django 3.1.5 on 2021-02-04 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20210204_1814'),
    ]
