# Generated by Django 3.1.5 on 2021-02-05 18:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20210205_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='end_bid_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 6, 19, 30, 40, 637847), verbose_name='Set bidding end time'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Upload image'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='start_bid_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 5, 19, 30, 40, 637847), verbose_name='Set bidding start time'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='starting_price',
            field=models.FloatField(verbose_name='Starting price (US $)'),
        ),
    ]
