# Generated by Django 3.1.5 on 2021-02-16 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0036_auto_20210216_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='highest_bid',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='highest_bid_currency',
        ),
    ]
