# Generated by Django 3.1.5 on 2021-02-19 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0041_user_watched_listings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='watched_listings',
            field=models.ManyToManyField(blank=True, to='auctions.Listing'),
        ),
    ]
