# Generated by Django 3.1.5 on 2021-02-19 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0044_auto_20210219_1853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='category',
        ),
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='auctions.category', verbose_name='Product category:'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='user_closed_bid',
            field=models.BooleanField(),
        ),
    ]
