# Generated by Django 3.1.7 on 2021-02-26 16:22

import auctions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0058_auto_20210226_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='time_difference',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=auctions.models.Listing.image_path, verbose_name='Upload image'),
        ),
    ]
