# Generated by Django 3.1.7 on 2021-03-04 15:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0065_auto_20210304_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, max_digits=1000000000000000000, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Shipping cost in US $:'),
        ),
    ]
