# Generated by Django 3.1.5 on 2021-02-04 16:09

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=255)),
                ('condition', models.CharField(max_length=64)),
                ('starting_bid', models.FloatField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('shipping_options', models.CharField(max_length=64)),
                ('shipping_cost', models.FloatField()),
                ('location', models.CharField(max_length=64)),
                ('time_listed', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auctions.category')),
            ],
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.AddField(
            model_name='user',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 2, 4, 17, 9, 27, 358784)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
