# Generated by Django 3.1.5 on 2021-02-05 16:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20210204_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='end_bid_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 6, 17, 35, 7, 637270)),
        ),
        migrations.AddField(
            model_name='listing',
            name='start_bid_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 5, 17, 35, 7, 637270)),
        ),
    ]
