# Generated by Django 3.1.5 on 2021-02-05 19:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auto_20210205_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='end_bid_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 6, 20, 7, 26, 244718), verbose_name='Set bidding end time'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='shipping_options',
            field=models.CharField(max_length=64, verbose_name='Ships to'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='start_bid_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 5, 20, 7, 26, 244718), verbose_name='Set bidding start time'),
        ),
    ]
