# Generated by Django 3.1.5 on 2021-02-07 17:27

import auctions.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_auto_20210206_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='end_bid_time',
            field=models.DateTimeField(verbose_name='Set bidding end time:'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to=auctions.models.Listing.image_path, verbose_name='Upload image'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='seller',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='listing',
            name='start_bid_time',
            field=models.DateTimeField(verbose_name='Set bidding start time:'),
        ),
    ]
