# Generated by Django 3.1.5 on 2021-02-08 09:40

from django.db import migrations
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_auto_20210207_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='time_zone',
            field=timezone_field.fields.TimeZoneField(verbose_name='Enter your time zone:'),
        ),
    ]
