# Generated by Django 3.1.5 on 2021-02-14 15:43

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0021_auto_20210212_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='location',
            field=django_countries.fields.CountryField(max_length=2, verbose_name='Location the product being sent from:'),
        ),
    ]
