# Generated by Django 3.1.5 on 2021-02-14 17:57

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0027_auto_20210214_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='shipping_cost',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), default_currency='USD', max_digits=19, verbose_name='Shipping cost:'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='starting_bid',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), default_currency='USD', max_digits=19, verbose_name='Starting bid:'),
        ),
    ]
