# Generated by Django 3.1.5 on 2021-02-16 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0034_auto_20210216_0929'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='listing_id',
            new_name='listing',
        ),
    ]
