# Generated by Django 3.1.5 on 2021-02-19 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0040_auto_20210217_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='watched_listings',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='auctions.Listing'),
        ),
    ]
