# Generated by Django 3.1.5 on 2021-02-19 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0043_listing_user_closed_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='category',
        ),
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.ManyToManyField(to='auctions.Category', verbose_name='Product category:'),
        ),
    ]
