# Generated by Django 3.1.7 on 2021-02-20 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0045_auto_20210219_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='user_closed_bid',
            field=models.BooleanField(default=False),
        ),
    ]
