# Generated by Django 3.1.7 on 2021-02-24 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0053_auto_20210224_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='increment',
            field=models.IntegerField(default=1),
        ),
    ]
