# Generated by Django 3.1.7 on 2021-02-26 15:10

import auctions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0057_remove_listing_user_closed_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.ImageField(blank=True, default='no_img.svg', null=True, upload_to=auctions.models.Listing.image_path, verbose_name='Upload image'),
        ),
    ]
