# Generated by Django 3.1.7 on 2021-02-26 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0059_auto_20210226_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='time_difference',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
