# Generated by Django 3.1.7 on 2021-03-04 15:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0063_auto_20210302_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='amount_bid_currency',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='current_bid_currency',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='highest_bid_currency',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='minimum_bid_currency',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='shipping_cost_currency',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='starting_bid_currency',
        ),
        migrations.AlterField(
            model_name='bid',
            name='amount_bid',
            field=models.DecimalField(decimal_places=2, max_digits=1000000000000000000, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000000000000000)], verbose_name='Place bid in US $:'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='current_bid',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=1000000000000000000, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000000000000000)], verbose_name='Current bid:'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='highest_bid',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=1000000000000000000, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000000000000000)], verbose_name='Highest bid:'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='minimum_bid',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=1000000000000000000, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000000000000000)], verbose_name='Minimum bid:'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, max_digits=1000000000000000000, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000000000000000)], verbose_name='Shipping cost:'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='starting_bid',
            field=models.DecimalField(decimal_places=2, max_digits=1000000000000000000, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Starting bid in US $:'),
        ),
    ]
